### ISSUE TITLE
filter is not working

### ISSUE THREAD

**Issue by MrPeanutss** [fagbokforlaget/nestjs-mongoose-paginate#26]
Hello everyone,

I tried to use your package for the filter part .
By using it with this url : `http://localhost:8000/formrecord?filter={"userName": {"$regex": "^test"}}`

I have these errors 
```
[Nest] 175  - 10/04/2022, 8:16:10 PM   ERROR [ExceptionsHandler] Unexpected token o in JSON at position 1
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at filterQueryToObject (/usr/src/app/node_modules/@forlagshuset/nestjs-mongoose-paginate/src/input.dto.ts:52:15)
    at Object.transformFn (/usr/src/app/node_modules/@forlagshuset/nestjs-mongoose-paginate/src/input.dto.ts:23:40)
    at /usr/src/app/node_modules/src/TransformOperationExecutor.ts:412:24
    at Array.forEach (<anonymous>)
    at TransformOperationExecutor.applyCustomTransformations (/usr/src/app/node_modules/src/TransformOperationExecutor.ts:411:15)
    at TransformOperationExecutor.transform (/usr/src/app/node_modules/src/TransformOperationExecutor.ts:317:31)
    at ClassTransformer.instanceToPlain (/usr/src/app/node_modules/src/ClassTransformer.ts:25:21)
    at Object.classToPlain (/usr/src/app/node_modules/src/index.ts:23:27)
    at ValidationPipe.transform (/usr/src/app/node_modules/@nestjs/common/pipes/validation.pipe.js:81:32)
```

It seems that the transformation between url and the validation pipe is broken ? Anyone faced to this issue ?

Thanks in advance

**Comment by iapain** [comment]
@MrPeanutss Did you try encoding your query string?
